### ISSUE TITLE
Nested modules not supported

### ISSUE THREAD

**Issue by JesusFreke** [ncsaba/idea-openscad#11]
Hi! I was just trying out the plugin and noticed that nested modules aren't supported.

e.g. (a simple, but stupid example)

    module thing() {
        module sub_thing(pos) {
            translate([0, pos, 0]) cylinder(10, 1, 1);
        }
        sub_thing(0);
        sub_thing(10);
    }
    thing();

I get a red squiggly on line 2 that says `<object>, OpenSCADTokenType.IDENTIFIER or OpenSCADTokenType.RBRACE expected, got 'module'`

**Comment by ncsaba** [comment]
Hi there, the grammar is unfortunately buggy in the current realeased version. I will push later today a newer one which solves all known parsing issues and adds structure view, but which is a WIP with basically half-done code navigation features in it. I hesitated pushing it because of this WIP status, but I guess it is better than having known bugs.

**Comment by JesusFreke** [comment]
Awesome, thanks.

Yeah, code navigation would be hugely helpful :) go to definition, find usages, all that fun stuff.
