### ISSUE TITLE
code completion does not work

### ISSUE THREAD

**Issue by jesperldk** [ncsaba/idea-openscad#26]
I'm on a build I did today.
Code completion does not work for my own code. It does work for the build in modules and functions, and it does work for the MCAD library, but not for my own project. It is a bit strange, because navigation to declaration works great for my own project.

**Comment by ldenisey** [comment]
Is your code split in several file or are you testing with a single file ?
Ideally, if you have a simple example, it would be great.

**Comment by jesperldk** [comment]
Ok, did try a few things, but am not sure quite what works in which situations.

If I make a new project with two files:

ta.scar:
````
module tamodule() {
    cube([5, 5, 5]);
}
````

t2.scar:
````
use <ta.scad>

tamodule(); // code completion does not work

t2var = "t2var";

module t2module(t2arg1,t2arg2) {
    echo(t2arg1); // code completions doe not work
    echo(t2var); // code completion does work
    tamodule(); // code completion does not work
}

t2module("a1","a2"); // code completion does work
````

You can see in the comment where code completion works for me. What is most strange is that in this small 2-file project ctrl-click (goto definition) does not work anywhere.

The project I am working on is: https://github.com/SmoothieAq/cevo
In this project ctrl-click seems to work everywhere (nice!), but code completion works as limited as in the small 2-file project.

I am hoping, that all this is easily fixable, as my larger cevo project seems to have good knowledge about all defined names (although it has little knowledge about scope). It would be great to have code completion against the same definitions that you ctrl-clik to goto.

And merry xmas :-)

**Comment by ldenisey** [comment]
Perfect, thank you for the example, I'll look into this.

**Comment by ldenisey** [comment]
Hello,

Solve those in #29. Tested manually with https://github.com/ldenisey/idea-openscad/blob/master/test/main/openscad/t2.scad. Can you give it a try and confirm with your project ?

**Comment by SmoothieAq** [comment]
Thanks!

More works now, but there are still problems and some strange workings. Sorry, by it will be a few more days before I can test it a bit more and give some better feedback.

--Jesper

**Comment by SmoothieAq** [comment]
Ok, found some more time today ;-)

Most works! Great work!

It does not show variables brought into scope with an include, but it does show modules brought into scope with either use or include.

The workings are somewhat confusing and different from how it works with Java.

When I start typing (for example "t" to get "tamodule" in my sample), it shows a completion-list that contains 

1. local vars 
2. local modules 
3. MCAD modules

But the list does *not* modules from my use or include. 

I can then press ctrl-space to get 

1. local vars 
2. local modules 
3. modules from use or include

That is what we want ;-) But confusing to get the other list first. In Java I get a list like the second one already when I start typing.
More seriously, if I press ctrl-space to get the second list, but what I have typed so far matches a single entry in the first list, it just (sometimes?) selects that entry instead of showing the second list.

ctrl-click to go to definition, seems to work mostly fine. However it does not work for functions, only for modules.
Also, it is strange, that ctrl-space only shows what is in scope from use or include, but ctrl-click can go to definitions that are not in scope? Preferable it should be the other way around ;-)

Let me know, if all this is clear, or if you would like some more examples and more precise descriptions.

**Comment by ldenisey** [comment]
Hello,

Was a bit busy, found some time this weekend to work a bit on the plugin.

I have added in master the code to display variables from includes.

Regarding the 2 lists, I have modified the behavior. The first list should show : 
- local vars
- vars from includes
- local modules and functions
- builtin modules and functions
- modules and functions from include/use

The second list should add from the first list modules and functions from all libraries that are configured in the project but not included or used in the file. Does it seems better now ?

Regarding ctrl+click, I have merged a fix this week end, can you confirm you still have the issue ?

**Comment by SmoothieAq** [comment]
Great!
It will be a few days, before I have the time to check it out.

I have actually been running on #29, as it was clearly better than master. There are however quite a few issues. In my opinion IntelliJ is already the best platform for OpenSCAD  programming, but things does stop working with larger files. Be prepared for some bug reports later on ;-)

--Jesper

**Comment by SmoothieAq** [comment]
Hey, a lot is working real nice now!
I will test some more, and then close this issue...

**Comment by SmoothieAq** [comment]
I am closing this one. Overall code completion and ctrl-click navigation works great, even in my large project with more than 50 files and thousands of lines of code.

That is just magical and a fantastic help in programming with OpenSCAD! :-D

I have reported a number of issues, and probably more will pop up as I use it, but this is a huge step forward!
